name: HGIS CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'linux'
        target: 'desktop'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          build-essential \
          libgdal-dev \
          libproj-dev \
          libgeos-dev \
          python3-dev \
          python3-pip \
          libsip-dev \
          python3-sip-dev \
          qgis-dev \
          libqgis-dev \
          qgis-common
        pip3 install sip

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test Python modules
      run: |
        cd ${{github.workspace}}
        python3 -m pytest python/tests/ -v
        
    - name: Test C++ modules
      run: |
        cd ${{github.workspace}}/build
        ctest -C ${{env.BUILD_TYPE}} --verbose

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Python linting tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black mypy
        
    - name: Lint Python code
      run: |
        flake8 python/hgis --max-line-length=120
        black --check python/hgis
        mypy python/hgis --ignore-missing-imports

    - name: Install cppcheck
      run: sudo apt-get install -y cppcheck
      
    - name: Lint C++ code  
      run: |
        find src -name "*.cpp" -o -name "*.h" | xargs cppcheck --enable=all --suppress=missingIncludeSystem

  package:
    needs: [test, lint]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          cmake \
          build-essential \
          libgdal-dev \
          libproj-dev \
          libgeos-dev \
          python3-dev \
          python3-pip \
          libsip-dev \
          python3-sip-dev \
          qgis-dev \
          libqgis-dev \
          qgis-common
          
    - name: Build Release
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
        
    - name: Create AppImage
      run: |
        # AppImage 패키징 스크립트 실행
        chmod +x scripts/package-appimage.sh
        ./scripts/package-appimage.sh
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: hgis-linux-x64
        path: |
          build/hgis
          *.AppImage